language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
script: make publish
deploy:
  provider: pages
  fqdn: amritbera.com
  skip-cleanup: true
  local-dir: output
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master